name: .Net Framework

on: 
  pull_request:
    paths:
      - 'src/*'
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .Net Framework
        uses: microsoft/setup-msbuild@v1.0.2
      - name: build
        run: | 
          msbuild src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj -t:restore
          msbuild src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj -p:Configuration=Release
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .Net Framework
        uses: rickedb/setup-msbuild@dev
      - name: build
        run: | 
          msbuild src/MIDTesters/MIDTesters.csproj -t:restore
          msbuild src/MIDTesters/MIDTesters.csproj
      - name: test
        run: mstest src/MIDTesters/bin/Debug/MIDTesters.dll