name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '2.1.202'
      - name: Build library (.net core)
        run: dotnet build src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj --configuration release
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and run .net core tests
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '2.1.202'
      - name: Test Mids
        run: |
          dotnet build src/MIDTesters.Core/MIDTesters.Core.csproj
          dotnet test src/MIDTesters.Core/MIDTesters.Core.csproj
  publish:
    needs: [build, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet
        run: |
          dotnet build src/OpenProtocolInterpreter/OpenProtocolInterpreter.csproj --configuration release
          nuget push src/OpenProtocolInterpreter/bin/release/OpenProtocolInterpreter.3.4.3.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate